### ISSUE TITLE
Frontend approbation: enable CSV output

### ISSUE THREAD

**Issue by edd** [vegaprotocol/jenkins-shared-library#304]
It's not currently enabled

# Tasks
- [x] Go to the core run, which has it enabled
- [x] Look at the parameters
- [x] Copy `--output-csv`
- [x] Paste it in to frontend run

**Comment by edd** [comment]
https://github.com/vegaprotocol/approbation/blob/main/README.md updated as a result of this
