### ISSUE TITLE
Add a second approbation run for frontend that categorises ACs by apps, not categories

### ISSUE THREAD

**Issue by edd** [vegaprotocol/jenkins-shared-library#420]
For frontend only, there are two different perspectives - Acceptance Criteria coverage by *category* and Acceptance Criteria coverage by *app*. To run both of these, we need to run approbation a second time with a different value for the `categories` parameter

# Tasks
- [x] Add a second `stage` that runs only for `frontend-monorepo`
- [x] Add a new argument that can be configured to select the categories file representing ACs by app
- [x] Make the new stage that that parameter for the `--categories` argument
    - [x]  Otherwise the run should be identical
