### ISSUE TITLE
Add new approbation param

### ISSUE THREAD

**Issue by edd** [vegaprotocol/jenkins-shared-library#751]
Approbation now accepts a string parameter `--current-milestone`. To make the transition easier, I made the code default to `colosseo_II`. It will be overriden when a new value is passed in

# Task
- [ ] Update groovy to accept a new configuration parameter, `CURRENT_MILESTONE`
- [ ] When that is set, pass it in to the command line as `--current-milestone="{CURRENT_MILESTONE}"
- [ ] Make the default/current value `colosseo_II`

When that milestone is complete, it will be change to `colosseo_III`. and after that `genbu_temple`. These values are coming from the `milestone` props of each value in https://github.com/vegaprotocol/specs/blob/colosseo_II/protocol/features.json
